version: "3"
services:
  app:
    container_name: 'tddbc'
    image: node:19
    working_dir: /usr/src/app
    tty: true
    ports:
    - '3000:3000'
    volumes:
      - ./src:/usr/src/app
    user: "1000:1000"